{
 "title": "Synthetic monitoring demo",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "data_source", "query": "elasticsearch" },
   {
    "name": "url",
    "query": "{ \"find\": \"terms\", \"field\": \"dimensions.url\", \"query\":\"type:synthetic-monitoring\"}"
   },
   {
    "name": "region",
    "query": "{ \"find\": \"terms\", \"field\": \"dimensions.region\", \"query\":\"type:synthetic-monitoring AND dimensions.url:$url\"}"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average load time by location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 1 },
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dimensions.country",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "10s", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "metrics.time_to_complete.ms",
       "id": "1",
       "inlineScript": "_value/1000",
       "meta": {},
       "settings": { "script": { "inline": "_value/1000" } },
       "type": "avg"
      }
     ],
     "query": "dimensions.url:$url AND dimensions.resource_type:\"webpage\" AND dimensions.region:$region",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Latest responses",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "@timestamp",
       "id": "6",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      },
      {
       "field": "dimensions.region",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "metrics.time_to_complete.ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "metrics.status_code",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "metrics.time_to_first_byte.ms",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "metrics.up",
       "hide": true,
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "dimensions.url:$url AND dimensions.resource_type:\"webpage\" AND dimensions.region:$region",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Time to DOM completion",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{dimensions.region}} ({{dimensions.country}})",
     "bucketAggs": [
      {
       "fake": true,
       "field": "dimensions.country",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "dimensions.region",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "metrics.time_to_complete.ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "dimensions.url:$url AND dimensions.resource_type:\"webpage\" AND dimensions.region:$region",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Resource metrics ($region)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "region",
   "collapsed": true,
   "panels": [
    {
     "title": "Resources ",
     "type": "table",
     "gridPos": { "h": 12, "w": 17, "x": 0, "y": 20 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "dimensions.resource_name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "dimensions.resource_type",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "metrics.time_to_complete.ms",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "dimensions.url:$url AND NOT dimensions.resource_type:\"webpage\" AND dimensions.region:$region",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Request time by resource type",
     "type": "stat",
     "gridPos": { "h": 12, "w": 7, "x": 17, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "dimensions.resource_type",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "metrics.time_to_complete.ms",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "dimensions.url:$url AND NOT dimensions.resource_type:(webpage OR we) AND dimensions.region:$region",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource metrics ($region)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resources ",
     "type": "table",
     "gridPos": { "h": 12, "w": 17, "x": 0, "y": 20 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "dimensions.resource_name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "dimensions.resource_type",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "metrics.time_to_complete.ms",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "dimensions.url:$url AND NOT dimensions.resource_type:\"webpage\" AND dimensions.region:$region",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Request time by resource type",
     "type": "stat",
     "gridPos": { "h": 12, "w": 7, "x": 17, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "dimensions.resource_type",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "metrics.time_to_complete.ms",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "dimensions.url:$url AND NOT dimensions.resource_type:(webpage OR we) AND dimensions.region:$region",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource metrics ($region)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resources ",
     "type": "table",
     "gridPos": { "h": 12, "w": 17, "x": 0, "y": 20 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "dimensions.resource_name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "dimensions.resource_type",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "metrics.time_to_complete.ms",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "dimensions.url:$url AND NOT dimensions.resource_type:\"webpage\" AND dimensions.region:$region",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Request time by resource type",
     "type": "stat",
     "gridPos": { "h": 12, "w": 7, "x": 17, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "dimensions.resource_type",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "metrics.time_to_complete.ms",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "dimensions.url:$url AND NOT dimensions.resource_type:(webpage OR we) AND dimensions.region:$region",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource metrics ($region)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resources ",
     "type": "table",
     "gridPos": { "h": 12, "w": 17, "x": 0, "y": 20 },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "dimensions.resource_name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "dimensions.resource_type",
         "id": "2",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "metrics.time_to_complete.ms",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "dimensions.url:$url AND NOT dimensions.resource_type:\"webpage\" AND dimensions.region:$region",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Request time by resource type",
     "type": "stat",
     "gridPos": { "h": 12, "w": 7, "x": 17, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "dimensions.resource_type",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "metrics.time_to_complete.ms",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "dimensions.url:$url AND NOT dimensions.resource_type:(webpage OR we) AND dimensions.region:$region",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}