AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function for synthetic monitoring.
Parameters:
  scrapeInterval:
    Type: String
    Description: Cloudwatch events rate schedule Expression. See https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#RateExpressions
    Default: "rate(5 minutes)"
  logzioRegion:
    Type: String
    Description: Logz.io Region Code
      for further information.
    Default: ""
  logzioURL:
    Type: String
    Description: Logz.io listener URL. See https://docs.logz.io/user-guide/accounts/account-region.html#regions-and-urls
      for further information.
    Default: ""
  url:
    Type: String
    Description: Url to monitor.
    Default: ''
  logzioMetricsToken:
    Type: String
    Description: Token for shipping metrics to your Logz.io account.
    Default: ''
  logzioLogsToken:
    Type: String
    Description: Token for shipping logs to your Logz.io account.
    Default: ''
  shippingProtocol:
    Type: String
    Description: Protocol for shipping metrics and logs.
    Default: https
  domComplete:
    Type: Number
    Description: Seconds to wait for page's dom elements to complete.
    Default: '5'
Resources:
  LogzioLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: Logzio-sm-lambda
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            - iam:GetRole
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
            - xray:GetSamplingRules
            - xray:GetSamplingTargets
            - xray:GetSamplingStatisticSummaries
            Resource: "*"
  LogzioSyntheticMonitoringFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: logzio-sm-{region_code}
        S3Key: lambda_function.zip
      Description: Python script for synthetic monitoring
      Handler: lambda_function/lambda_function.lambda_handler
      Role: !GetAtt LogzioLambdaExecutionRole.Arn
      Runtime: python3.7
      Timeout: 180
      MemorySize: 512
      Environment:
        Variables:
          LOGZIO_CUSTOM_LISTENER:
            Ref: logzioURL
          LOGZIO_REGION:
            Ref: logzioRegion
          URL:
            Ref: url
          LOGZIO_METRICS_TOKEN:
            Ref: logzioMetricsToken
          LOGZIO_LOGS_TOKEN:
            Ref: logzioLogsToken
          PROTOCOL:
            Ref: shippingProtocol
          DOM_COMPLETE:
            Ref: domComplete
      Layers:
      - Ref: LogzioSyntheticMonitoringBinLayer
      - Ref: LogzioSyntheticMonitoringPythonLayer
  LogzioSyntheticMonitoringBinLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
      - python3.7
      Content:
        S3Bucket: logzio-sm-{region_code}
        S3Key: bin.zip
      Description: Binaries of Chromium & Chromedriver for synthetic monitoring
      LayerName: synthetic-monitoring-bin
  LogzioSyntheticMonitoringPythonLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
      - python3.7
      Content:
        S3Bucket: logzio-sm-{region_code}
        S3Key: python.zip
      Description: Selenium & Requests imported modules.
      LayerName: synthetic-monitoring-python
  LogzioScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "LogzioScheduledRule"
      ScheduleExpression:
        Ref: scrapeInterval
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt 
            - LogzioSyntheticMonitoringFunction
            - Arn
          Id: TargetFunctionV1
  LogzioPermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: LogzioSyntheticMonitoringFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - LogzioScheduledRule
        - Arn
